### ISSUE TITLE
Верстка Jetro Contact

### ISSUE THREAD

**Issue by Erjan-Emilbekov** [Erjan-Emilbekov/html_group_9_teamwork_team_2#10]
Нужно свертать Jetro Contact и вёрсткой этого макета займется Мухидин
2. План выполнения
      - Сделать вёрстку без хедера и футера в Tester-Project-Folder (1)
      - Сверстать полностью макет в contact.html (2)
      - В папке css добавить папку contact и туда скопировать стили для (1) верстки (3)
3. Мотивация 
      С меня час PS4 (бесплатно)
4. Критерий готовности
      - Проверка на кроссбраузерность: Chrome, Opera, Microsoft Edge, Firefox Mozilla
      - Проверка на адаптивность для телефонов и для планшетов
5. Время по плану и по факту
      - Мухидин тебе 3 часа на всю вверстку
      - И напишите сколько по факту ушло времени

**Comment by MonkeyDjack** [comment]
готово
время по факту 2 часа
