### ISSUE TITLE
верстка блока с ссылками и блока с последними работами

### ISSUE THREAD

**Issue by MonkeyDjack** [Erjan-Emilbekov/html_group_9_teamwork_team_2#3]
#Задача 
сверстать блоки после слайдера с сылками "more" и блоком с недавними работами
##Требование 
 кроссбраузерность и адаптивность
##Примечания
блоки с недавней работай сверстать в техническом файле "portfolio_block.html"

**Comment by baigazytb** [comment]
Блок с ссылками сверстал

**Comment by baigazytb** [comment]
Сверстал блока после ссылки 'more'
все верстки **слайдер** и **ссылка и блок после ссылки** находится в папке **_'slider'_**
