### ISSUE TITLE
Верстка блока portfolio plugin из макета jetro_portfolio_item

### ISSUE THREAD

**Issue by baigazytb** [Erjan-Emilbekov/html_group_9_teamwork_team_2#7]
### Задачи 
Сверстать блок portfolio plugin

### Решение 
Можно сверстать блок с помощью слайдер плагинов

### Требование 
кроссбраузерность и адаптивность

**Comment by baigazytb** [comment]
Сверстан блок portfolio plugin

**Comment by MonkeyDjack** [comment]
доверстал всю страницу вместе с portfolio item
