### ISSUE TITLE
Верстка Jetro Portfolio 

### ISSUE THREAD

**Issue by Erjan-Emilbekov** [Erjan-Emilbekov/html_group_9_teamwork_team_2#8]
1.  Нужно свертать Jetro Portfolio и хотелось бы разделить его в два этапа 
      1)Обычная верстка PSD макета (которую берёт Байгазы байке) 
      2)Фильтрация блоков работ(которую берет Мухидин) 

2. План выполнения 
      - Я создам новую папку которую назову Tester_Project_Folder, туда скопирую все верстку которую мы до этого сделали. 
      - Там создаете папку как в PSD и делает работу там. 
      - Мухидин если хочешь потестировать создай test.js внутри папки JS
3. Мотивация 
          Я тут недавно смотрел америцанские и европейские сайты, в основном в поисках работы и там нужны были люда в команду с зарплатой 3000$ и выше, мы же ведь хотим такую зарплату. Езе у намм нужна скидка, так что нужно постаратся.
4. Критерий готовности 
       - Проверка на кроссбраузерность: Chrome, Opera, Microsoft Edge, Firefox Mozilla
       - Проверка на адаптивность для телефонов и для планшетов 
       - Проверка на оптимизацию изображении [Сайт для общей проверки(только если проект размещен на сервере)](https://developers.google.com/speed/pagespeed/insights/)  #К выполненю не обезателе#
       - Pixel  Perfect обезателен
5. Время по плану и по факту 
        - Мне кажется Байгазы байке вам нужно 2 часа на вестку блоков 
        - Мухидин тебе 2 часа на сам скрипт и 3 часа на поиски плагина 
        - И напишите сколько по факту ушло времени

**Comment by baigazytb** [comment]
Сверстал блок с фильтрацию. Всю работу сделал около 3 часов.
А так же сверстал обычную верстку PSD макета. На эту ушло около 45 минут.
