### ISSUE TITLE
Jetro Portfolio Item

### ISSUE THREAD

**Issue by Erjan-Emilbekov** [Erjan-Emilbekov/html_group_9_teamwork_team_2#9]
1.  Нужно свертать Jetro Portfolio  Item и вёрсткой этого макета займется Мухидин
2. План выполнения
      - Сделать вёрстку без хедера и футера в Tester-Project-Folder (1)
      - Сверстать полностью макет в portfolio-item.html (2)
      - В папке css добавить папку portfolio-item и туда скопировать стили для (1) верстки (3)
3. Мотивация 
      С меня час PS4 (бесплатно)
4. Критерий готовности
      - Проверка на кроссбраузерность: Chrome, Opera, Microsoft Edge, Firefox Mozilla
      - Проверка на адаптивность для телефонов и для планшетов
5. Время по плану и по факту
      - Мухидин тебе 2 часа на всю вверстку
      - И напишите сколько по факту ушло времени

**Comment by MonkeyDjack** [comment]
сделано! 
время по плану 2 часа
по факту 1,5
